/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    agencies: Agency;
    postcards: Postcard;
    templates: Template;
    reactions: Reaction;
    comments: Comment;
    'postcard-view-events': PostcardViewEvent;
    'postcard-tracking-links': PostcardTrackingLink;
    'gallery-categories': GalleryCategory;
    'gallery-tags': GalleryTag;
    gallery: Gallery;
    stickers: Sticker;
    leads: Lead;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    postcards: PostcardsSelect<false> | PostcardsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    reactions: ReactionsSelect<false> | ReactionsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'postcard-view-events': PostcardViewEventsSelect<false> | PostcardViewEventsSelect<true>;
    'postcard-tracking-links': PostcardTrackingLinksSelect<false> | PostcardTrackingLinksSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    'gallery-tags': GalleryTagsSelect<false> | GalleryTagsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    stickers: StickersSelect<false> | StickersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'agence' | 'client' | 'user';
  /**
   * Agence liée au compte (pour rôle Agence ou Client).
   */
  agency?: (number | null) | Agency;
  company?: string | null;
  cardsCreated?: number | null;
  plan?: ('free' | 'pro' | 'enterprise') | null;
  magicLinkToken?: string | null;
  magicLinkExpires?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: number;
  name: string;
  code?: string | null;
  address?: string | null;
  city?: string | null;
  region?: string | null;
  country?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  primaryColor?: string | null;
  imageBank?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  qrCodeUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  exif?: {
    gps?: {
      /**
       * Latitude GPS extraite de l'image
       */
      latitude?: number | null;
      /**
       * Longitude GPS extraite de l'image
       */
      longitude?: number | null;
    };
    /**
     * Date et heure de la prise de vue (EXIF)
     */
    dateTime?: string | null;
    /**
     * Fabricant de l'appareil photo
     */
    cameraMake?: string | null;
    /**
     * Modèle de l'appareil photo
     */
    cameraModel?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postcards".
 */
export interface Postcard {
  id: number;
  publicId: string;
  frontImage?: (number | null) | Media;
  /**
   * URL for template images
   */
  frontImageURL?: string | null;
  /**
   * Texte court affiché sur la face avant
   */
  frontCaption?: string | null;
  /**
   * Emoji affiché près du texte de la face avant
   */
  frontEmoji?: string | null;
  /**
   * Position du bloc caption+emoji sur la face (x, y en % 0-100, centre du bloc)
   */
  frontCaptionPosition?: {
    x?: number | null;
    y?: number | null;
  };
  message: string;
  recipients?:
    | {
        email?: string | null;
        phone?: string | null;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  recipientName?: string | null;
  senderName?: string | null;
  senderEmail?: string | null;
  location?: string | null;
  coords?: {
    lat?: number | null;
    lng?: number | null;
  };
  stampStyle?: ('classic' | 'modern' | 'airmail') | null;
  stampLabel?: string | null;
  stampYear?: string | null;
  postmarkText?: string | null;
  date: string;
  status?: ('published' | 'draft' | 'archived') | null;
  views?: number | null;
  shares?: number | null;
  mediaItems?:
    | {
        media?: (number | null) | Media;
        type?: ('image' | 'video') | null;
        /**
         * Note ou légende pour cette photo/vidéo
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  isPremium?: boolean | null;
  agency?: (number | null) | Agency;
  brandLogo?: (number | null) | Media;
  author?: (number | null) | User;
  /**
   * Liste des autocollants placés sur la carte (ID, x, y, scale, rotation)
   */
  stickers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Autoriser les commentaires sur cette carte
   */
  allowComments?: boolean | null;
  /**
   * Si décoché, la carte sera privée et non listée
   */
  isPublic?: boolean | null;
  /**
   * Token secret pour permettre à des tiers d’ajouter des photos
   */
  contributionToken?: string | null;
  /**
   * Autoriser l’ajout de photos via le lien de contribution
   */
  isContributionEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  imageUrl: number | Media;
  category: 'beach' | 'city' | 'nature' | 'travel' | 'romantic' | 'festive' | 'food' | 'abstract';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions".
 */
export interface Reaction {
  id: number;
  postcard: number | Postcard;
  emoji: string;
  sessionId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  postcard: number | Postcard;
  authorName: string;
  content: string;
  sessionId: string;
  /**
   * If true, this comment will only be visible to the recipient.
   */
  isPrivate?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postcard-view-events".
 */
export interface PostcardViewEvent {
  id: number;
  postcard: number | Postcard;
  /**
   * Heure d'ouverture de la carte
   */
  openedAt: string;
  /**
   * Heure de fermeture (si enregistrée)
   */
  closedAt?: string | null;
  /**
   * Temps de vue en secondes
   */
  durationSeconds?: number | null;
  /**
   * User-Agent du navigateur
   */
  userAgent?: string | null;
  /**
   * Navigateur (parsé)
   */
  browser?: string | null;
  /**
   * Système d'exploitation (parsé)
   */
  os?: string | null;
  /**
   * Referrer de la page
   */
  referrer?: string | null;
  /**
   * Pays (depuis headers ou geo)
   */
  country?: string | null;
  /**
   * Code pays (ex. FR)
   */
  countryCode?: string | null;
  /**
   * Région
   */
  region?: string | null;
  /**
   * Ville
   */
  city?: string | null;
  /**
   * ID de session visiteur (déduplication)
   */
  sessionId: string;
  /**
   * Lien de tracking si la vue provient de /v/[token]
   */
  trackingLink?: (number | null) | PostcardTrackingLink;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postcard-tracking-links".
 */
export interface PostcardTrackingLink {
  id: number;
  postcard: number | Postcard;
  /**
   * Identifiant court pour l’URL /v/[token]
   */
  token: string;
  recipientFirstName?: string | null;
  recipientLastName?: string | null;
  description?: string | null;
  sentVia?: ('link' | 'email' | 'whatsapp' | 'sms') | null;
  /**
   * Date d’envoi (email / WhatsApp / SMS)
   */
  sentAt?: string | null;
  views?: number | null;
  author: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  /**
   * Agence propriétaire de cette catégorie (laisser vide pour les catégories globales)
   */
  agency?: (number | null) | Agency;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-tags".
 */
export interface GalleryTag {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Agence propriétaire de ce tag (laisser vide pour les tags globaux)
   */
  agency?: (number | null) | Agency;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  image: number | Media;
  caption?: string | null;
  /**
   * Catégorie de la photo
   */
  category?: (number | null) | GalleryCategory;
  /**
   * Tags pour filtrer et rechercher
   */
  tags?: (number | GalleryTag)[] | null;
  /**
   * Ordre d'affichage (plus petit = en premier)
   */
  order?: number | null;
  /**
   * Agence propriétaire de cette image (laisser vide pour les images globales)
   */
  agency?: (number | null) | Agency;
  views?: number | null;
  /**
   * Nombre de fois où cette image a été utilisée sur une carte postale
   */
  usages?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stickers".
 */
export interface Sticker {
  id: number;
  name: string;
  image: number | Media;
  category?: ('deco' | 'travel' | 'love' | 'fun' | 'vintage') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  email: string;
  /**
   * Code de remise unique généré pour ce lead
   */
  code: string;
  isUsed?: boolean | null;
  usedAt?: string | null;
  source?: string | null;
  /**
   * La carte postale qui a utilisé ce code
   */
  usedByPostcard?: (number | null) | Postcard;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  publishedDate?: string | null;
  author?: (number | null) | User;
  category?: ('travel' | 'lifestyle' | 'tips' | 'news') | null;
  /**
   * Un court résumé pour les cartes et le SEO
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'agencies';
        value: number | Agency;
      } | null)
    | ({
        relationTo: 'postcards';
        value: number | Postcard;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'reactions';
        value: number | Reaction;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'postcard-view-events';
        value: number | PostcardViewEvent;
      } | null)
    | ({
        relationTo: 'postcard-tracking-links';
        value: number | PostcardTrackingLink;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: number | GalleryCategory;
      } | null)
    | ({
        relationTo: 'gallery-tags';
        value: number | GalleryTag;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'stickers';
        value: number | Sticker;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  agency?: T;
  company?: T;
  cardsCreated?: T;
  plan?: T;
  magicLinkToken?: T;
  magicLinkExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  exif?:
    | T
    | {
        gps?:
          | T
          | {
              latitude?: T;
              longitude?: T;
            };
        dateTime?: T;
        cameraMake?: T;
        cameraModel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  address?: T;
  city?: T;
  region?: T;
  country?: T;
  phone?: T;
  email?: T;
  website?: T;
  logo?: T;
  primaryColor?: T;
  imageBank?:
    | T
    | {
        image?: T;
        id?: T;
      };
  qrCodeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postcards_select".
 */
export interface PostcardsSelect<T extends boolean = true> {
  publicId?: T;
  frontImage?: T;
  frontImageURL?: T;
  frontCaption?: T;
  frontEmoji?: T;
  frontCaptionPosition?:
    | T
    | {
        x?: T;
        y?: T;
      };
  message?: T;
  recipients?:
    | T
    | {
        email?: T;
        phone?: T;
        name?: T;
        id?: T;
      };
  recipientName?: T;
  senderName?: T;
  senderEmail?: T;
  location?: T;
  coords?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  stampStyle?: T;
  stampLabel?: T;
  stampYear?: T;
  postmarkText?: T;
  date?: T;
  status?: T;
  views?: T;
  shares?: T;
  mediaItems?:
    | T
    | {
        media?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  isPremium?: T;
  agency?: T;
  brandLogo?: T;
  author?: T;
  stickers?: T;
  allowComments?: T;
  isPublic?: T;
  contributionToken?: T;
  isContributionEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  imageUrl?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions_select".
 */
export interface ReactionsSelect<T extends boolean = true> {
  postcard?: T;
  emoji?: T;
  sessionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  postcard?: T;
  authorName?: T;
  content?: T;
  sessionId?: T;
  isPrivate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postcard-view-events_select".
 */
export interface PostcardViewEventsSelect<T extends boolean = true> {
  postcard?: T;
  openedAt?: T;
  closedAt?: T;
  durationSeconds?: T;
  userAgent?: T;
  browser?: T;
  os?: T;
  referrer?: T;
  country?: T;
  countryCode?: T;
  region?: T;
  city?: T;
  sessionId?: T;
  trackingLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postcard-tracking-links_select".
 */
export interface PostcardTrackingLinksSelect<T extends boolean = true> {
  postcard?: T;
  token?: T;
  recipientFirstName?: T;
  recipientLastName?: T;
  description?: T;
  sentVia?: T;
  sentAt?: T;
  views?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  agency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-tags_select".
 */
export interface GalleryTagsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  agency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  caption?: T;
  category?: T;
  tags?: T;
  order?: T;
  agency?: T;
  views?: T;
  usages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stickers_select".
 */
export interface StickersSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  email?: T;
  code?: T;
  isUsed?: T;
  usedAt?: T;
  source?: T;
  usedByPostcard?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  author?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  image?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}