/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  numeric,
  serial,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'agence', 'client', 'user'])
export const enum_users_plan = pgEnum('enum_users_plan', ['free', 'pro', 'enterprise'])
export const enum_postcards_media_items_type = pgEnum('enum_postcards_media_items_type', [
  'image',
  'video',
])
export const enum_postcards_front_caption_font_family = pgEnum(
  'enum_postcards_front_caption_font_family',
  ['serif', 'sans', 'cursive', 'display'],
)
export const enum_postcards_front_caption_color = pgEnum('enum_postcards_front_caption_color', [
  'stone-900',
  'white',
  'black',
  'teal-800',
  'stone-700',
  'amber-900',
  'rose-900',
  'emerald-900',
])
export const enum_postcards_event_type = pgEnum('enum_postcards_event_type', [
  'birthday',
  'vacation',
  'invitation',
  'birth',
  'christmas',
  'wedding',
  'graduation',
])
export const enum_postcards_stamp_style = pgEnum('enum_postcards_stamp_style', [
  'classic',
  'modern',
  'airmail',
])
export const enum_postcards_status = pgEnum('enum_postcards_status', [
  'published',
  'draft',
  'archived',
])
export const enum_postcards_puzzle_card_difficulty = pgEnum(
  'enum_postcards_puzzle_card_difficulty',
  ['3', '4', '5'],
)
export const enum_templates_category = pgEnum('enum_templates_category', [
  'beach',
  'city',
  'nature',
  'travel',
  'romantic',
  'festive',
  'food',
  'abstract',
])
export const enum_postcard_tracking_links_sent_via = pgEnum(
  'enum_postcard_tracking_links_sent_via',
  ['link', 'email', 'whatsapp', 'sms'],
)
export const enum_stickers_category = pgEnum('enum_stickers_category', [
  'deco',
  'travel',
  'love',
  'fun',
  'vintage',
])
export const enum_posts_category = pgEnum('enum_posts_category', [
  'travel',
  'lifestyle',
  'tips',
  'news',
])
export const enum_posts_status = pgEnum('enum_posts_status', ['draft', 'published'])
export const enum_email_templates_target_role = pgEnum('enum_email_templates_target_role', [
  'all',
  'client',
  'agence',
])
export const enum_feedback_status = pgEnum('enum_feedback_status', ['new', 'read', 'processed'])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', { mode: 'string', withTimezone: true, precision: 3 }),
    userAgent: varchar('user_agent'),
    ip: varchar('ip'),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users_accounts = pgTable(
  'users_accounts',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    provider: varchar('provider').notNull(),
    providerAccountId: varchar('provider_account_id').notNull(),
    type: varchar('type').notNull(),
  },
  (columns) => [
    index('users_accounts_order_idx').on(columns._order),
    index('users_accounts_parent_id_idx').on(columns._parentID),
    index('users_accounts_provider_account_id_idx').on(columns.providerAccountId),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_accounts_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: varchar('id').primaryKey(),
    emailVerified: timestamp('email_verified', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    name: varchar('name'),
    image: varchar('image'),
    role: enum_users_role('role').notNull().default('user'),
    agency: integer('agency_id').references(() => agencies.id, {
      onDelete: 'set null',
    }),
    company: varchar('company'),
    cardsCreated: numeric('cards_created', { mode: 'number' }).default(0),
    plan: enum_users_plan('plan').default('free'),
    credits: numeric('credits', { mode: 'number' }).default(0),
    magicLinkToken: varchar('magic_link_token'),
    magicLinkExpires: timestamp('magic_link_expires', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    mobileUploadCode: varchar('mobile_upload_code'),
    mobileUploadCodeExpires: timestamp('mobile_upload_code_expires', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_agency_idx').on(columns.agency),
    index('users_mobile_upload_code_idx').on(columns.mobileUploadCode),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    exif_gps_latitude: numeric('exif_gps_latitude', { mode: 'number' }),
    exif_gps_longitude: numeric('exif_gps_longitude', { mode: 'number' }),
    exif_dateTime: timestamp('exif_date_time', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    exif_cameraMake: varchar('exif_camera_make'),
    exif_cameraModel: varchar('exif_camera_model'),
    location: varchar('location'),
    author: varchar('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_author_idx').on(columns.author),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const agencies_image_bank = pgTable(
  'agencies_image_bank',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('agencies_image_bank_order_idx').on(columns._order),
    index('agencies_image_bank_parent_id_idx').on(columns._parentID),
    index('agencies_image_bank_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [agencies.id],
      name: 'agencies_image_bank_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const agencies = pgTable(
  'agencies',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    code: varchar('code'),
    address: varchar('address'),
    city: varchar('city'),
    region: varchar('region'),
    country: varchar('country').default('France'),
    phone: varchar('phone'),
    email: varchar('email'),
    website: varchar('website'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    primaryColor: varchar('primary_color'),
    qrCodeUrl: varchar('qr_code_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('agencies_code_idx').on(columns.code),
    index('agencies_logo_idx').on(columns.logo),
    index('agencies_updated_at_idx').on(columns.updatedAt),
    index('agencies_created_at_idx').on(columns.createdAt),
  ],
)

export const postcards_recipients = pgTable(
  'postcards_recipients',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    email: varchar('email'),
    phone: varchar('phone'),
    name: varchar('name'),
  },
  (columns) => [
    index('postcards_recipients_order_idx').on(columns._order),
    index('postcards_recipients_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [postcards.id],
      name: 'postcards_recipients_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const postcards_media_items = pgTable(
  'postcards_media_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    type: enum_postcards_media_items_type('type').default('image'),
    note: varchar('note'),
  },
  (columns) => [
    index('postcards_media_items_order_idx').on(columns._order),
    index('postcards_media_items_parent_id_idx').on(columns._parentID),
    index('postcards_media_items_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [postcards.id],
      name: 'postcards_media_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const postcards = pgTable(
  'postcards',
  {
    id: serial('id').primaryKey(),
    publicId: varchar('public_id').notNull(),
    frontImage: integer('front_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    frontImageURL: varchar('front_image_u_r_l'),
    frontCaption: varchar('front_caption'),
    frontEmoji: varchar('front_emoji'),
    frontCaptionPosition_x: numeric('front_caption_position_x', { mode: 'number' }).default(50),
    frontCaptionPosition_y: numeric('front_caption_position_y', { mode: 'number' }).default(85),
    frontCaptionFontFamily: enum_postcards_front_caption_font_family('front_caption_font_family'),
    frontCaptionFontSize: numeric('front_caption_font_size', { mode: 'number' }),
    frontCaptionColor: enum_postcards_front_caption_color('front_caption_color'),
    frontTextBgOpacity: numeric('front_text_bg_opacity', { mode: 'number' }),
    frontCaptionPreset: varchar('front_caption_preset'),
    frontCaptionWidth: numeric('front_caption_width', { mode: 'number' }),
    message: varchar('message').notNull(),
    recipientName: varchar('recipient_name'),
    senderName: varchar('sender_name'),
    senderEmail: varchar('sender_email'),
    location: varchar('location'),
    coords_lat: numeric('coords_lat', { mode: 'number' }),
    coords_lng: numeric('coords_lng', { mode: 'number' }),
    eventType: enum_postcards_event_type('event_type'),
    stampStyle: enum_postcards_stamp_style('stamp_style').default('classic'),
    stampLabel: varchar('stamp_label'),
    stampYear: varchar('stamp_year'),
    postmarkText: varchar('postmark_text'),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    status: enum_postcards_status('status').default('draft'),
    views: numeric('views', { mode: 'number' }).default(0),
    shares: numeric('shares', { mode: 'number' }).default(0),
    isPremium: boolean('is_premium').default(false),
    agency: integer('agency_id').references(() => agencies.id, {
      onDelete: 'set null',
    }),
    brandLogo: integer('brand_logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    author: varchar('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    stickers: jsonb('stickers'),
    allowComments: boolean('allow_comments').default(true),
    isPublic: boolean('is_public').default(true),
    contributionToken: varchar('contribution_token'),
    isContributionEnabled: boolean('is_contribution_enabled').default(true),
    scratchCardEnabled: boolean('scratch_card_enabled').default(false),
    scratchCardImage: integer('scratch_card_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    puzzleCardEnabled: boolean('puzzle_card_enabled').default(false),
    puzzleCardDifficulty:
      enum_postcards_puzzle_card_difficulty('puzzle_card_difficulty').default('3'),
    audioMessage: varchar('audio_message'),
    audioDuration: numeric('audio_duration', { mode: 'number' }),
    backgroundMusic: varchar('background_music'),
    backgroundMusicTitle: varchar('background_music_title'),
    hideMap: boolean('hide_map').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('postcards_public_id_idx').on(columns.publicId),
    index('postcards_front_image_idx').on(columns.frontImage),
    index('postcards_agency_idx').on(columns.agency),
    index('postcards_brand_logo_idx').on(columns.brandLogo),
    index('postcards_author_idx').on(columns.author),
    index('postcards_contribution_token_idx').on(columns.contributionToken),
    index('postcards_scratch_card_image_idx').on(columns.scratchCardImage),
    index('postcards_updated_at_idx').on(columns.updatedAt),
    index('postcards_created_at_idx').on(columns.createdAt),
  ],
)

export const templates = pgTable(
  'templates',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    imageUrl: integer('image_url_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    category: enum_templates_category('category').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('templates_image_url_idx').on(columns.imageUrl),
    index('templates_updated_at_idx').on(columns.updatedAt),
    index('templates_created_at_idx').on(columns.createdAt),
  ],
)

export const reactions = pgTable(
  'reactions',
  {
    id: serial('id').primaryKey(),
    postcard: integer('postcard_id')
      .notNull()
      .references(() => postcards.id, {
        onDelete: 'set null',
      }),
    emoji: varchar('emoji').notNull(),
    sessionId: varchar('session_id').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('reactions_postcard_idx').on(columns.postcard),
    index('reactions_session_id_idx').on(columns.sessionId),
    index('reactions_updated_at_idx').on(columns.updatedAt),
    index('reactions_created_at_idx').on(columns.createdAt),
  ],
)

export const comments = pgTable(
  'comments',
  {
    id: serial('id').primaryKey(),
    postcard: integer('postcard_id')
      .notNull()
      .references(() => postcards.id, {
        onDelete: 'set null',
      }),
    authorName: varchar('author_name').notNull(),
    content: varchar('content').notNull(),
    sessionId: varchar('session_id').notNull(),
    isPrivate: boolean('is_private').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('comments_postcard_idx').on(columns.postcard),
    index('comments_updated_at_idx').on(columns.updatedAt),
    index('comments_created_at_idx').on(columns.createdAt),
  ],
)

export const postcard_view_events = pgTable(
  'postcard_view_events',
  {
    id: serial('id').primaryKey(),
    postcard: integer('postcard_id')
      .notNull()
      .references(() => postcards.id, {
        onDelete: 'set null',
      }),
    openedAt: timestamp('opened_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    closedAt: timestamp('closed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    durationSeconds: numeric('duration_seconds', { mode: 'number' }),
    userAgent: varchar('user_agent'),
    browser: varchar('browser'),
    os: varchar('os'),
    referrer: varchar('referrer'),
    country: varchar('country'),
    countryCode: varchar('country_code'),
    region: varchar('region'),
    city: varchar('city'),
    sessionId: varchar('session_id').notNull(),
    trackingLink: integer('tracking_link_id').references(() => postcard_tracking_links.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('postcard_view_events_postcard_idx').on(columns.postcard),
    index('postcard_view_events_session_id_idx').on(columns.sessionId),
    index('postcard_view_events_tracking_link_idx').on(columns.trackingLink),
    index('postcard_view_events_updated_at_idx').on(columns.updatedAt),
    index('postcard_view_events_created_at_idx').on(columns.createdAt),
  ],
)

export const postcard_tracking_links = pgTable(
  'postcard_tracking_links',
  {
    id: serial('id').primaryKey(),
    postcard: integer('postcard_id')
      .notNull()
      .references(() => postcards.id, {
        onDelete: 'set null',
      }),
    token: varchar('token').notNull(),
    recipientFirstName: varchar('recipient_first_name'),
    recipientLastName: varchar('recipient_last_name'),
    description: varchar('description'),
    sentVia: enum_postcard_tracking_links_sent_via('sent_via'),
    sentAt: timestamp('sent_at', { mode: 'string', withTimezone: true, precision: 3 }),
    views: numeric('views', { mode: 'number' }).default(0),
    author: varchar('author_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('postcard_tracking_links_postcard_idx').on(columns.postcard),
    uniqueIndex('postcard_tracking_links_token_idx').on(columns.token),
    index('postcard_tracking_links_author_idx').on(columns.author),
    index('postcard_tracking_links_updated_at_idx').on(columns.updatedAt),
    index('postcard_tracking_links_created_at_idx').on(columns.createdAt),
  ],
)

export const gallery_categories = pgTable(
  'gallery_categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    generateSlug: boolean('generate_slug').default(true),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    agency: integer('agency_id').references(() => agencies.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('gallery_categories_slug_idx').on(columns.slug),
    index('gallery_categories_agency_idx').on(columns.agency),
    index('gallery_categories_updated_at_idx').on(columns.updatedAt),
    index('gallery_categories_created_at_idx').on(columns.createdAt),
  ],
)

export const gallery_tags = pgTable(
  'gallery_tags',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    generateSlug: boolean('generate_slug').default(true),
    slug: varchar('slug').notNull(),
    agency: integer('agency_id').references(() => agencies.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('gallery_tags_slug_idx').on(columns.slug),
    index('gallery_tags_agency_idx').on(columns.agency),
    index('gallery_tags_updated_at_idx').on(columns.updatedAt),
    index('gallery_tags_created_at_idx').on(columns.createdAt),
  ],
)

export const gallery = pgTable(
  'gallery',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
    category: integer('category_id').references(() => gallery_categories.id, {
      onDelete: 'set null',
    }),
    order: numeric('order', { mode: 'number' }).default(0),
    agency: integer('agency_id').references(() => agencies.id, {
      onDelete: 'set null',
    }),
    views: numeric('views', { mode: 'number' }).default(0),
    usages: numeric('usages', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('gallery_image_idx').on(columns.image),
    index('gallery_category_idx').on(columns.category),
    index('gallery_agency_idx').on(columns.agency),
    index('gallery_updated_at_idx').on(columns.updatedAt),
    index('gallery_created_at_idx').on(columns.createdAt),
  ],
)

export const gallery_rels = pgTable(
  'gallery_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'gallery-tagsID': integer('gallery_tags_id'),
  },
  (columns) => [
    index('gallery_rels_order_idx').on(columns.order),
    index('gallery_rels_parent_idx').on(columns.parent),
    index('gallery_rels_path_idx').on(columns.path),
    index('gallery_rels_gallery_tags_id_idx').on(columns['gallery-tagsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [gallery.id],
      name: 'gallery_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['gallery-tagsID']],
      foreignColumns: [gallery_tags.id],
      name: 'gallery_rels_gallery_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const stickers = pgTable(
  'stickers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    category: enum_stickers_category('category').default('deco'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('stickers_image_idx').on(columns.image),
    index('stickers_updated_at_idx').on(columns.updatedAt),
    index('stickers_created_at_idx').on(columns.createdAt),
  ],
)

export const leads = pgTable(
  'leads',
  {
    id: serial('id').primaryKey(),
    email: varchar('email').notNull(),
    code: varchar('code').notNull(),
    isUsed: boolean('is_used').default(false),
    usedAt: timestamp('used_at', { mode: 'string', withTimezone: true, precision: 3 }),
    source: varchar('source').default('exit-intent'),
    usedByPostcard: integer('used_by_postcard_id').references(() => postcards.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('leads_email_idx').on(columns.email),
    uniqueIndex('leads_code_idx').on(columns.code),
    index('leads_used_by_postcard_idx').on(columns.usedByPostcard),
    index('leads_updated_at_idx').on(columns.updatedAt),
    index('leads_created_at_idx').on(columns.createdAt),
  ],
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    author: varchar('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    category: enum_posts_category('category'),
    excerpt: varchar('excerpt'),
    content: jsonb('content').notNull(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    status: enum_posts_status('status').default('draft'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug),
    index('posts_author_idx').on(columns.author),
    index('posts_image_idx').on(columns.image),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
  ],
)

export const email_templates = pgTable(
  'email_templates',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    subject: varchar('subject').notNull(),
    body: varchar('body').notNull(),
    targetRole: enum_email_templates_target_role('target_role').default('all'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('email_templates_updated_at_idx').on(columns.updatedAt),
    index('email_templates_created_at_idx').on(columns.createdAt),
  ],
)

export const feedback = pgTable(
  'feedback',
  {
    id: serial('id').primaryKey(),
    rating: numeric('rating', { mode: 'number' }),
    message: varchar('message').notNull(),
    email: varchar('email'),
    pageUrl: varchar('page_url'),
    user: varchar('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    status: enum_feedback_status('status').default('new'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('feedback_user_idx').on(columns.user),
    index('feedback_updated_at_idx').on(columns.updatedAt),
    index('feedback_created_at_idx').on(columns.createdAt),
  ],
)

export const editor_previews = pgTable(
  'editor_previews',
  {
    id: serial('id').primaryKey(),
    token: varchar('token').notNull(),
    data: jsonb('data').notNull(),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('editor_previews_token_idx').on(columns.token),
    index('editor_previews_updated_at_idx').on(columns.updatedAt),
    index('editor_previews_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: varchar('users_id'),
    mediaID: integer('media_id'),
    agenciesID: integer('agencies_id'),
    postcardsID: integer('postcards_id'),
    templatesID: integer('templates_id'),
    reactionsID: integer('reactions_id'),
    commentsID: integer('comments_id'),
    'postcard-view-eventsID': integer('postcard_view_events_id'),
    'postcard-tracking-linksID': integer('postcard_tracking_links_id'),
    'gallery-categoriesID': integer('gallery_categories_id'),
    'gallery-tagsID': integer('gallery_tags_id'),
    galleryID: integer('gallery_id'),
    stickersID: integer('stickers_id'),
    leadsID: integer('leads_id'),
    postsID: integer('posts_id'),
    'email-templatesID': integer('email_templates_id'),
    feedbackID: integer('feedback_id'),
    'editor-previewsID': integer('editor_previews_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_agencies_id_idx').on(columns.agenciesID),
    index('payload_locked_documents_rels_postcards_id_idx').on(columns.postcardsID),
    index('payload_locked_documents_rels_templates_id_idx').on(columns.templatesID),
    index('payload_locked_documents_rels_reactions_id_idx').on(columns.reactionsID),
    index('payload_locked_documents_rels_comments_id_idx').on(columns.commentsID),
    index('payload_locked_documents_rels_postcard_view_events_id_idx').on(
      columns['postcard-view-eventsID'],
    ),
    index('payload_locked_documents_rels_postcard_tracking_links_id_idx').on(
      columns['postcard-tracking-linksID'],
    ),
    index('payload_locked_documents_rels_gallery_categories_id_idx').on(
      columns['gallery-categoriesID'],
    ),
    index('payload_locked_documents_rels_gallery_tags_id_idx').on(columns['gallery-tagsID']),
    index('payload_locked_documents_rels_gallery_id_idx').on(columns.galleryID),
    index('payload_locked_documents_rels_stickers_id_idx').on(columns.stickersID),
    index('payload_locked_documents_rels_leads_id_idx').on(columns.leadsID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_email_templates_id_idx').on(columns['email-templatesID']),
    index('payload_locked_documents_rels_feedback_id_idx').on(columns.feedbackID),
    index('payload_locked_documents_rels_editor_previews_id_idx').on(columns['editor-previewsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['agenciesID']],
      foreignColumns: [agencies.id],
      name: 'payload_locked_documents_rels_agencies_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postcardsID']],
      foreignColumns: [postcards.id],
      name: 'payload_locked_documents_rels_postcards_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['templatesID']],
      foreignColumns: [templates.id],
      name: 'payload_locked_documents_rels_templates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['reactionsID']],
      foreignColumns: [reactions.id],
      name: 'payload_locked_documents_rels_reactions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['commentsID']],
      foreignColumns: [comments.id],
      name: 'payload_locked_documents_rels_comments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postcard-view-eventsID']],
      foreignColumns: [postcard_view_events.id],
      name: 'payload_locked_documents_rels_postcard_view_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postcard-tracking-linksID']],
      foreignColumns: [postcard_tracking_links.id],
      name: 'payload_locked_documents_rels_postcard_tracking_links_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['gallery-categoriesID']],
      foreignColumns: [gallery_categories.id],
      name: 'payload_locked_documents_rels_gallery_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['gallery-tagsID']],
      foreignColumns: [gallery_tags.id],
      name: 'payload_locked_documents_rels_gallery_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['galleryID']],
      foreignColumns: [gallery.id],
      name: 'payload_locked_documents_rels_gallery_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['stickersID']],
      foreignColumns: [stickers.id],
      name: 'payload_locked_documents_rels_stickers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['leadsID']],
      foreignColumns: [leads.id],
      name: 'payload_locked_documents_rels_leads_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['email-templatesID']],
      foreignColumns: [email_templates.id],
      name: 'payload_locked_documents_rels_email_templates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['feedbackID']],
      foreignColumns: [feedback.id],
      name: 'payload_locked_documents_rels_feedback_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['editor-previewsID']],
      foreignColumns: [editor_previews.id],
      name: 'payload_locked_documents_rels_editor_previews_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: varchar('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const settings = pgTable('settings', {
  id: serial('id').primaryKey(),
  exitIntentEnabled: boolean('exit_intent_enabled').default(true),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users_accounts = relations(users_accounts, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_accounts._parentID],
    references: [users.id],
    relationName: 'accounts',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  agency: one(agencies, {
    fields: [users.agency],
    references: [agencies.id],
    relationName: 'agency',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
  accounts: many(users_accounts, {
    relationName: 'accounts',
  }),
}))
export const relations_media = relations(media, ({ one }) => ({
  author: one(users, {
    fields: [media.author],
    references: [users.id],
    relationName: 'author',
  }),
}))
export const relations_agencies_image_bank = relations(agencies_image_bank, ({ one }) => ({
  _parentID: one(agencies, {
    fields: [agencies_image_bank._parentID],
    references: [agencies.id],
    relationName: 'imageBank',
  }),
  image: one(media, {
    fields: [agencies_image_bank.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_agencies = relations(agencies, ({ one, many }) => ({
  logo: one(media, {
    fields: [agencies.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  imageBank: many(agencies_image_bank, {
    relationName: 'imageBank',
  }),
}))
export const relations_postcards_recipients = relations(postcards_recipients, ({ one }) => ({
  _parentID: one(postcards, {
    fields: [postcards_recipients._parentID],
    references: [postcards.id],
    relationName: 'recipients',
  }),
}))
export const relations_postcards_media_items = relations(postcards_media_items, ({ one }) => ({
  _parentID: one(postcards, {
    fields: [postcards_media_items._parentID],
    references: [postcards.id],
    relationName: 'mediaItems',
  }),
  media: one(media, {
    fields: [postcards_media_items.media],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_postcards = relations(postcards, ({ one, many }) => ({
  frontImage: one(media, {
    fields: [postcards.frontImage],
    references: [media.id],
    relationName: 'frontImage',
  }),
  recipients: many(postcards_recipients, {
    relationName: 'recipients',
  }),
  mediaItems: many(postcards_media_items, {
    relationName: 'mediaItems',
  }),
  agency: one(agencies, {
    fields: [postcards.agency],
    references: [agencies.id],
    relationName: 'agency',
  }),
  brandLogo: one(media, {
    fields: [postcards.brandLogo],
    references: [media.id],
    relationName: 'brandLogo',
  }),
  author: one(users, {
    fields: [postcards.author],
    references: [users.id],
    relationName: 'author',
  }),
  scratchCardImage: one(media, {
    fields: [postcards.scratchCardImage],
    references: [media.id],
    relationName: 'scratchCardImage',
  }),
}))
export const relations_templates = relations(templates, ({ one }) => ({
  imageUrl: one(media, {
    fields: [templates.imageUrl],
    references: [media.id],
    relationName: 'imageUrl',
  }),
}))
export const relations_reactions = relations(reactions, ({ one }) => ({
  postcard: one(postcards, {
    fields: [reactions.postcard],
    references: [postcards.id],
    relationName: 'postcard',
  }),
}))
export const relations_comments = relations(comments, ({ one }) => ({
  postcard: one(postcards, {
    fields: [comments.postcard],
    references: [postcards.id],
    relationName: 'postcard',
  }),
}))
export const relations_postcard_view_events = relations(postcard_view_events, ({ one }) => ({
  postcard: one(postcards, {
    fields: [postcard_view_events.postcard],
    references: [postcards.id],
    relationName: 'postcard',
  }),
  trackingLink: one(postcard_tracking_links, {
    fields: [postcard_view_events.trackingLink],
    references: [postcard_tracking_links.id],
    relationName: 'trackingLink',
  }),
}))
export const relations_postcard_tracking_links = relations(postcard_tracking_links, ({ one }) => ({
  postcard: one(postcards, {
    fields: [postcard_tracking_links.postcard],
    references: [postcards.id],
    relationName: 'postcard',
  }),
  author: one(users, {
    fields: [postcard_tracking_links.author],
    references: [users.id],
    relationName: 'author',
  }),
}))
export const relations_gallery_categories = relations(gallery_categories, ({ one }) => ({
  agency: one(agencies, {
    fields: [gallery_categories.agency],
    references: [agencies.id],
    relationName: 'agency',
  }),
}))
export const relations_gallery_tags = relations(gallery_tags, ({ one }) => ({
  agency: one(agencies, {
    fields: [gallery_tags.agency],
    references: [agencies.id],
    relationName: 'agency',
  }),
}))
export const relations_gallery_rels = relations(gallery_rels, ({ one }) => ({
  parent: one(gallery, {
    fields: [gallery_rels.parent],
    references: [gallery.id],
    relationName: '_rels',
  }),
  'gallery-tagsID': one(gallery_tags, {
    fields: [gallery_rels['gallery-tagsID']],
    references: [gallery_tags.id],
    relationName: 'gallery-tags',
  }),
}))
export const relations_gallery = relations(gallery, ({ one, many }) => ({
  image: one(media, {
    fields: [gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
  category: one(gallery_categories, {
    fields: [gallery.category],
    references: [gallery_categories.id],
    relationName: 'category',
  }),
  agency: one(agencies, {
    fields: [gallery.agency],
    references: [agencies.id],
    relationName: 'agency',
  }),
  _rels: many(gallery_rels, {
    relationName: '_rels',
  }),
}))
export const relations_stickers = relations(stickers, ({ one }) => ({
  image: one(media, {
    fields: [stickers.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_leads = relations(leads, ({ one }) => ({
  usedByPostcard: one(postcards, {
    fields: [leads.usedByPostcard],
    references: [postcards.id],
    relationName: 'usedByPostcard',
  }),
}))
export const relations_posts = relations(posts, ({ one }) => ({
  author: one(users, {
    fields: [posts.author],
    references: [users.id],
    relationName: 'author',
  }),
  image: one(media, {
    fields: [posts.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_email_templates = relations(email_templates, () => ({}))
export const relations_feedback = relations(feedback, ({ one }) => ({
  user: one(users, {
    fields: [feedback.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_editor_previews = relations(editor_previews, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    agenciesID: one(agencies, {
      fields: [payload_locked_documents_rels.agenciesID],
      references: [agencies.id],
      relationName: 'agencies',
    }),
    postcardsID: one(postcards, {
      fields: [payload_locked_documents_rels.postcardsID],
      references: [postcards.id],
      relationName: 'postcards',
    }),
    templatesID: one(templates, {
      fields: [payload_locked_documents_rels.templatesID],
      references: [templates.id],
      relationName: 'templates',
    }),
    reactionsID: one(reactions, {
      fields: [payload_locked_documents_rels.reactionsID],
      references: [reactions.id],
      relationName: 'reactions',
    }),
    commentsID: one(comments, {
      fields: [payload_locked_documents_rels.commentsID],
      references: [comments.id],
      relationName: 'comments',
    }),
    'postcard-view-eventsID': one(postcard_view_events, {
      fields: [payload_locked_documents_rels['postcard-view-eventsID']],
      references: [postcard_view_events.id],
      relationName: 'postcard-view-events',
    }),
    'postcard-tracking-linksID': one(postcard_tracking_links, {
      fields: [payload_locked_documents_rels['postcard-tracking-linksID']],
      references: [postcard_tracking_links.id],
      relationName: 'postcard-tracking-links',
    }),
    'gallery-categoriesID': one(gallery_categories, {
      fields: [payload_locked_documents_rels['gallery-categoriesID']],
      references: [gallery_categories.id],
      relationName: 'gallery-categories',
    }),
    'gallery-tagsID': one(gallery_tags, {
      fields: [payload_locked_documents_rels['gallery-tagsID']],
      references: [gallery_tags.id],
      relationName: 'gallery-tags',
    }),
    galleryID: one(gallery, {
      fields: [payload_locked_documents_rels.galleryID],
      references: [gallery.id],
      relationName: 'gallery',
    }),
    stickersID: one(stickers, {
      fields: [payload_locked_documents_rels.stickersID],
      references: [stickers.id],
      relationName: 'stickers',
    }),
    leadsID: one(leads, {
      fields: [payload_locked_documents_rels.leadsID],
      references: [leads.id],
      relationName: 'leads',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    'email-templatesID': one(email_templates, {
      fields: [payload_locked_documents_rels['email-templatesID']],
      references: [email_templates.id],
      relationName: 'email-templates',
    }),
    feedbackID: one(feedback, {
      fields: [payload_locked_documents_rels.feedbackID],
      references: [feedback.id],
      relationName: 'feedback',
    }),
    'editor-previewsID': one(editor_previews, {
      fields: [payload_locked_documents_rels['editor-previewsID']],
      references: [editor_previews.id],
      relationName: 'editor-previews',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_settings = relations(settings, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_users_plan: typeof enum_users_plan
  enum_postcards_media_items_type: typeof enum_postcards_media_items_type
  enum_postcards_front_caption_font_family: typeof enum_postcards_front_caption_font_family
  enum_postcards_front_caption_color: typeof enum_postcards_front_caption_color
  enum_postcards_event_type: typeof enum_postcards_event_type
  enum_postcards_stamp_style: typeof enum_postcards_stamp_style
  enum_postcards_status: typeof enum_postcards_status
  enum_postcards_puzzle_card_difficulty: typeof enum_postcards_puzzle_card_difficulty
  enum_templates_category: typeof enum_templates_category
  enum_postcard_tracking_links_sent_via: typeof enum_postcard_tracking_links_sent_via
  enum_stickers_category: typeof enum_stickers_category
  enum_posts_category: typeof enum_posts_category
  enum_posts_status: typeof enum_posts_status
  enum_email_templates_target_role: typeof enum_email_templates_target_role
  enum_feedback_status: typeof enum_feedback_status
  users_sessions: typeof users_sessions
  users_accounts: typeof users_accounts
  users: typeof users
  media: typeof media
  agencies_image_bank: typeof agencies_image_bank
  agencies: typeof agencies
  postcards_recipients: typeof postcards_recipients
  postcards_media_items: typeof postcards_media_items
  postcards: typeof postcards
  templates: typeof templates
  reactions: typeof reactions
  comments: typeof comments
  postcard_view_events: typeof postcard_view_events
  postcard_tracking_links: typeof postcard_tracking_links
  gallery_categories: typeof gallery_categories
  gallery_tags: typeof gallery_tags
  gallery: typeof gallery
  gallery_rels: typeof gallery_rels
  stickers: typeof stickers
  leads: typeof leads
  posts: typeof posts
  email_templates: typeof email_templates
  feedback: typeof feedback
  editor_previews: typeof editor_previews
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  settings: typeof settings
  relations_users_sessions: typeof relations_users_sessions
  relations_users_accounts: typeof relations_users_accounts
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_agencies_image_bank: typeof relations_agencies_image_bank
  relations_agencies: typeof relations_agencies
  relations_postcards_recipients: typeof relations_postcards_recipients
  relations_postcards_media_items: typeof relations_postcards_media_items
  relations_postcards: typeof relations_postcards
  relations_templates: typeof relations_templates
  relations_reactions: typeof relations_reactions
  relations_comments: typeof relations_comments
  relations_postcard_view_events: typeof relations_postcard_view_events
  relations_postcard_tracking_links: typeof relations_postcard_tracking_links
  relations_gallery_categories: typeof relations_gallery_categories
  relations_gallery_tags: typeof relations_gallery_tags
  relations_gallery_rels: typeof relations_gallery_rels
  relations_gallery: typeof relations_gallery
  relations_stickers: typeof relations_stickers
  relations_leads: typeof relations_leads
  relations_posts: typeof relations_posts
  relations_email_templates: typeof relations_email_templates
  relations_feedback: typeof relations_feedback
  relations_editor_previews: typeof relations_editor_previews
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_settings: typeof relations_settings
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
